# Generated by Django 5.0.1 on 2024-02-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_remove_book_topics_remove_book_price_alter_book_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=2083)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'unique_together': {('title', 'author')},
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
