# Generated by Django 5.0.1 on 2024-02-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_book_delete_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default=' ', max_length=100000),
            preserve_default=False,
        ),
    ]
