# Generated by Django 4.2.5 on 2024-02-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.CharField(max_length=100000),
        ),
    ]
